=== vstrimaitis/InternetTechnologies/Task2/wordSearchPuzzle.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://vstrimaitis.github.io/puzzle"
    elementFormDefault="qualified"
    
    xmlns:this="http://vstrimaitis.github.io/puzzle"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <!--xmlns="http://vstrimaitis.github.io/puzzle" -->

  <!-- TYPE DECLARATIONS -->
  <!--1-->
  <xs:simpleType name="WordType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]+" />
    </xs:restriction>
  </xs:simpleType>

  <!--2-->
  <!--The time it took people to finish the puzzle-->
  <xs:simpleType name="ResultHistoryList">
    <xs:list itemType="xs:int" />
  </xs:simpleType>
  
  <!--3.2-->
  <xs:complexType name="HintWordType">
    <xs:simpleContent>
      <xs:extension base="this:WordType">
        <xs:attribute name="id" type="xs:int" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <!--3.1-->
  <!--pzl:col will now have id attribute-->
  <xs:complexType name="GridColumnType">
    <xs:simpleContent>
      <xs:restriction base="this:HintWordType">
        <xs:maxLength value="1" />
        <xs:minLength value="1" />
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="GridUnknownColumnType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="?" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="GridRowType">
    <xs:sequence>
      <!--7-->
      <xs:choice maxOccurs="unbounded">
        <xs:element name="col" type="this:GridColumnType" />
        <xs:element name="colUnknown" type="this:GridUnknownColumnType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="CoordinateContainer">
    <xs:sequence>
      <xs:element name="row" type="this:GridRowType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="col" type="this:GridColumnType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!--4.1-->
  <xs:complexType name="GridType">
    <xs:complexContent>
      <xs:restriction base="this:CoordinateContainer">
        <xs:sequence>
          <xs:element name="row" type="this:GridRowType" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TypeWithId">
    <xs:attribute name="id" type="xs:int" use="required" />
  </xs:complexType>

  <!--5
  <xs:complexType name="TypeWithIdAndAlias">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:int" use="required" />
        <xs:attribute name="alias" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="BadTypeWithId">
    <xs:simpleContent>
      <xs:restriction base="this:TypeWithIdAndAlias">
        <xs:attribute name="id" type="xs:int" use="prohibited" />
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="GoodTypeWithId">
    <xs:simpleContent>
      <xs:restriction base="this:TypeWithIdAndAlias">
        <xs:attribute name="id" type="xs:int" use="required" />
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>
  -->
  
  <xs:complexType name="PointType">
    <xs:attribute name="row" type="xs:int" />
    <xs:attribute name="col" type="xs:int" />
  </xs:complexType>

  <xs:complexType name="TurnsListType">
    <xs:sequence>
      <xs:element name="turn" type="this:PointType" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <!--4.2-->
  <xs:complexType name="SolutionWordType">
    <xs:complexContent>
      <xs:extension base="this:TypeWithId">
        <xs:sequence>
          <xs:element name="start" type="this:PointType" />
          <xs:element name="end" type="this:PointType" />
          <xs:element name="turns" type="this:TurnsListType" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <!--6-->
  <xs:complexType name="DescriptionType" mixed="true">
    <xs:sequence>
      <xs:element name="h" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  
  <!--7-->
  
  
  <!-- Other -->
  <xs:complexType name="PuzzleType">
    <xs:sequence>
      <xs:element name="description" type="this:DescriptionType" />
      <xs:element name="resultHistory" type="this:ResultHistoryList" />
      <xs:element name="words" type="this:HintWordsListType" />
      <xs:element name="grid" type="this:GridType" />
      <xs:element name="solution" type="this:SolutionType" />
    </xs:sequence>
    <xs:attribute name="width" type="xs:int" />
    <xs:attribute name="height" type="xs:int" />
    <xs:attribute name="difficulty" type="xs:decimal" />
    <xs:attribute name="creationDate" type="xs:date" />
  </xs:complexType>

  <xs:complexType name="HintWordsListType">
    <xs:sequence>
      <xs:element name="word" type="this:HintWordType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SolutionType">
    <xs:sequence>
      <xs:element name="word" type="this:SolutionWordType" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <!-- XML STRUCTURE DECLARATION -->
  <xs:element name="puzzle" type="this:PuzzleType">
    <!--8-->
    <xs:key name="WordIdKey">
      <xs:selector xpath="this:words/this:word" />
      <xs:field xpath="@id" />
    </xs:key>
    <xs:keyref name="SolutionWordRef" refer="this:WordIdKey">
      <xs:selector xpath="this:solution/this:word" />
      <xs:field xpath="@id" />
    </xs:keyref>
  </xs:element>
  
</xs:schema>

=== vstrimaitis/InternetTechnologies/Task2/wordSearchPuzzle.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pzl:puzzle width="6"
            height="6"
            difficulty="3.5"
            creationDate="2017-09-28"
            xmlns="http://vstrimaitis.github.io/puzzle"
            xmlns:pzl="http://vstrimaitis.github.io/puzzle"
            xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://vstrimaitis.github.io/puzzle wordSearchPuzzle.xsd"
>
  <description>
    This is a <h>very</h> nice description.
  </description>
  <resultHistory>
    16 15 20 60 404
  </resultHistory>
  <pzl:words>
    <pzl:word id="0">JAVASCRIPT</pzl:word>
    <pzl:word id="1">XPATH</pzl:word>
    <pzl:word id="2">JSON</pzl:word>
    <pzl:word id="3">SCHEMA</pzl:word>
    <pzl:word id="4">HTML</pzl:word>
    <pzl:word id="5">CSS</pzl:word>
    <pzl:word id="6">INTERNETAS</pzl:word>
    <pzl:word id="7">WIFI</pzl:word>
  </pzl:words>
  <pzl:grid>
    <pzl:row>
      <pzl:col>J</pzl:col>
      <pzl:col>R</pzl:col>
      <pzl:col>I</pzl:col>
      <pzl:col>T</pzl:col>
      <pzl:col>N</pzl:col>
      <pzl:col>T</pzl:col>
      <pzl:colUnknown>?</pzl:colUnknown>
    </pzl:row>
    <pzl:row>
      <pzl:col>A</pzl:col>
      <pzl:col>C</pzl:col>
      <pzl:col>P</pzl:col>
      <pzl:col>C</pzl:col>
      <pzl:col>I</pzl:col>
      <pzl:col>M</pzl:col>
      <pzl:col>E</pzl:col>
    </pzl:row>
    <pzl:row>
      <pzl:col>V</pzl:col>
      <pzl:col>S</pzl:col>
      <pzl:col>L</pzl:col>
      <pzl:col>S</pzl:col>
      <pzl:col>E</pzl:col>
      <pzl:col>R</pzl:col>
      <pzl:col>N</pzl:col>
    </pzl:row>
    <pzl:row>
      <pzl:col>A</pzl:col>
      <pzl:col>Y</pzl:col>
      <pzl:col>L</pzl:col>
      <pzl:col>H</pzl:col>
      <pzl:col>S</pzl:col>
      <pzl:col>E</pzl:col>
      <pzl:col>T</pzl:col>
    </pzl:row>
    <pzl:row>
      <pzl:col>X</pzl:col>
      <pzl:col>H</pzl:col>
      <pzl:col>C</pzl:col>
      <pzl:col>M</pzl:col>
      <pzl:col>W</pzl:col>
      <pzl:col>I</pzl:col>
      <pzl:col>A</pzl:col>
    </pzl:row>
    <pzl:row>
      <pzl:col>P</pzl:col>
      <pzl:col>S</pzl:col>
      <pzl:col>T</pzl:col>
      <pzl:col>X</pzl:col>
      <pzl:col>I</pzl:col>
      <pzl:col>F</pzl:col>
      <pzl:col>S</pzl:col>
    </pzl:row>
    <pzl:row>
      <pzl:col>A</pzl:col>
      <pzl:col>T</pzl:col>
      <pzl:col>H</pzl:col>
      <pzl:col>J</pzl:col>
      <pzl:col>S</pzl:col>
      <pzl:col>O</pzl:col>
      <pzl:col>N</pzl:col>
    </pzl:row>
  </pzl:grid>
  <solution>
    <word id="0">
      <start row="0" col="0"/>
      <end row="0" col="3"/>
      <turns>
        <turn row="3" col="0"/>
        <turn row="2" col="1"/>
        <turn row="0" col="1"/>
        <turn row="0" col="2"/>
        <turn row="1" col="2"/>
      </turns>
    </word>
    <word id="1">
      <start row="4" col="0"/>
      <end row="6" col="2"/>
      <turns>
        <turn row="6" col="0"/>
      </turns>
    </word>
    <word id="2">
      <start row="6" col="3"/>
      <end row="6" col="6"/>
      <turns/>
    </word>
    <word id="3">
      <start row="5" col="1"/>
      <end row="0" col="6"/>
      <turns/>
    </word>
    <word id="4">
      <start row="4" col="1"/>
      <end row="3" col="2"/>
      <turns>
        <turn row="5" col="2"/>
        <turn row="4" col="3"/>
      </turns>
    </word>
    <word id="5">
      <start row="1" col="3"/>
      <end row="3" col="4"/>
      <turns>
        <turn row="2" col="3"/>
      </turns>
    </word>
    <word id="6">
      <start row="1" col="4"/>
      <end row="5" col="6"/>
      <turns>
        <turn row="0" col="4"/>
        <turn row="0" col="5"/>
        <turn row="1" col="6"/>
        <turn row="2" col="5"/>
        <turn row="2" col="6"/>
        <turn row="3" col="5"/>
        <turn row="3" col="6"/>
      </turns>
    </word>
    <word id="7">
      <start row="4" col="4"/>
      <end row="5" col="4"/>
      <turns>
        <turn row="4" col="5"/>
        <turn row="5" col="5"/>
      </turns>
    </word>
  </solution>
</pzl:puzzle>
